// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOEQOcSbmedwh7d4dx0B9EZWYDn0YzkpE',
    appId: '1:367623850817:web:a6a54a5bdd9731bffe2fc0',
    messagingSenderId: '367623850817',
    projectId: 'fir-cli-demo-1b242',
    authDomain: 'fir-cli-demo-1b242.firebaseapp.com',
    storageBucket: 'fir-cli-demo-1b242.firebasestorage.app',
    measurementId: 'G-9Y0J827E8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqr076mZ83XAtOc3eZobv47CiOfU24RTk',
    appId: '1:367623850817:android:5208f59cb0b951d1fe2fc0',
    messagingSenderId: '367623850817',
    projectId: 'fir-cli-demo-1b242',
    storageBucket: 'fir-cli-demo-1b242.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN3u6VMtdeIH38F2e6MA4rOQqNPe4mjB0',
    appId: '1:367623850817:ios:72d1c7abddfe5ad8fe2fc0',
    messagingSenderId: '367623850817',
    projectId: 'fir-cli-demo-1b242',
    storageBucket: 'fir-cli-demo-1b242.firebasestorage.app',
    iosBundleId: 'com.example.expensetracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOEQOcSbmedwh7d4dx0B9EZWYDn0YzkpE',
    appId: '1:367623850817:web:521cc8ea08404125fe2fc0',
    messagingSenderId: '367623850817',
    projectId: 'fir-cli-demo-1b242',
    authDomain: 'fir-cli-demo-1b242.firebaseapp.com',
    storageBucket: 'fir-cli-demo-1b242.firebasestorage.app',
    measurementId: 'G-CYMSS43NE4',
  );
}
